author: seedante
github_url: https://github.com/seedante/SDEDownloadManager/
root_url: https://seedante.github.io/SDEDownloadManager/
module: SDEDownloadManager
output: docs
theme: apple
module_version: 0.9.0
swift_version: "4.0.3"
